#include <pgmspace.h>

#define SECRET
#define THINGNAME "esp32_test"

const char WIFI_SSID[] = "xxxxxx";
const char WIFI_PASSWORD[] = "xxxxxxxx";
const char AWS_IOT_ENDPOINT[] = "a3ey8fsc2z6gz-ats.iot.us-east-1.amazonaws.com";

// Amazon Root CA 1
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

// Device Certificate
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUcxNCjSjUDowbewAa6k1ghbWddYowDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIxMDgwNjEyMjcw
NloXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0
ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMbx5bbkobdECtnosVda
9Mp0HPQWmJ6FyQEa55Tbyw1uxVQ/hZcW0hV9uTnfgOh3h1EcvC48A8o3GzCfa8tj
ckA332tk31OmMt6eN/jzMjIdSB2M/G2+gx3cWWQ29KnnRtCKN+OnwUSfZOgB10Kg
qERx97e8IuX6oAC5O6QzJ9roBVzWsjmfy7CFgJyLynpfDJX3TVrIBnV00dsgRIce
+Vjrx8HpPm6pqYLc3jglrteInNZKOkpwnZz4aadskq9d3xHhZwc2JVXqjYW/EFqW
S3nRpcoJ1CuTBXOCJOi77xANtfkxA46MZ2RGTvKM6hhnyomshd6tmO+stC95fYDm
3skCAwEAAaNgMF4wHwYDVR0jBBgwFoAUuGJsb1VyHEMtOEZ/TKNrBxaEsTkwHQYD
VR0OBBYEFO2Ld1laL4/ogmbcEFHAjwzkLLbcMAwGA1UdEwEB/wQCMAAwDgYDVR0P
AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQAUqov2QdG8wTweGpSQ65OzoYRE
uQYe8gr8gmL5+GbF980iRiM3Zrv02KQ25LkXTJKDzKEcKTCf+GjeL4iGHtrtAYeI
HWRgwr2XfyUQVMUQwP8lHx8BOCE0EbX3JHaf8NcRBVMC5K5U8X7DUsxrl9I+YyKx
dNh0gF4g/PT5T/LrMiQZLU3eDQLlp0geDHzyqEdNTAhQ0DzJnGxN95NmnavWHlfi
DBkCSe84NWohN61WrXNLiiT7yGWCG543WAqQE+jPwbyQGdOcd+LwBDkexeyuX4Xa
331fWMGfbJcRdS1COagWjZJ6HszME3iQBYGgDGXwFmEWaZ9rB0DFOxo4YLyu
-----END CERTIFICATE-----
)KEY";

// Device Private Key
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----

-----END RSA PRIVATE KEY-----
)KEY";
